name: Build RPM and DEB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up RPM build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm

      - name: Build RPM
        run: |
          rpmbuild -ba ~/rpmbuild/SPECS/count_files.spec

      - name: Build DEB
        run: |

