name: Build RPM and DEB Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm
        sudo apt-get install -y build-essential

    - name: Run count_files.sh
      run: |
        sudo ./count_files.sh --check_dir=/etc


