name: Build RPM and DEB

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install rpm dpkg-dev -y

    - name: Build RPM
      run: |
        mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        cp file_count.sh ~/rpmbuild/SOURCES/
        rpmbuild -ba file_count.spec

    - name: Build DEB
      run: |
        mkdir -p ~/debpackage/DEBIAN ~/debpackage/usr/local/bin
        cp file_count.sh ~/debpackage/usr/local/bin/
        dpkg-deb --build ~/debpackage
